apiVersion: v1
kind: Service
metadata:
  name: myapi-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ca-central-1:862980915839:certificate/5ca967a8-fc03-4217-b80e-573225969afd
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  selector:
    app: myapi
  ports:
    - port: 8080
      name: http
      targetPort: 8080
